export const text = {
  splashText:"Sparkle & Shine Transform Your Drive with Every Wash!",
  letstart:"Let's Start",
  haveanAcc:"Already have an Account ",
  signIn:"Sign In",
  welcomeBack:"Hi! Welcome Back, you have been missed",
  dontHaveAcc:"Don't have an Account ",
  terms:"By Login & Sign up,you agree to our teams of use and Privacy policy",
  signUp:"Sign Up",
  password:"Password",
  phone:"Phone",
  name:"Name",
  forgetPassword:"Forget Password",
  agree:"Agree with",
  conditionText:"Terms & Condition",
  fillin:"Fill in the below form and add life to your cart.",
  welcome:"Welcome",
  logout:"Logout",
};